### PR TITLE
enable grant_services_security_admin_role feature

### LINKED ISSUE #740: GKE app failed to start due to Load Balancer health check firewall rule cannot be created in VPC host project
This issue has happened few times. Just want to document the issue and solutions here. 

When using DPT or CFT's GKE modules to create the cluster, it also adds health check. And when the VPC is hosted in a separate project, the GKE Service Agent fail to create a firewall rule for HC and potentially other ones (not always predictable). The support has been added in PF module as https://github.com/terraform-google-modules/terraform-google-project-factory/pull/483 and https://github.com/terraform-google-modules/terraform-google-project-factory/pull/536. We need to include that in DPT.

### PR DESCRIPTION
**Pull request by xingao267**
Fixes #740
#658

### CODE REVIEW

**Review by umairidris — COMMENTED** [review]
I think we should make this a manually configurable field. It only applies to the apps project. You could also force set it to true when gke clusters are defined.

**Comment by xingao267** [comment]
The underlying Project Factory module already imposes a [condition](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/shared_vpc_access/main.tf#L89) on whether or not container.googleapis.com is enabled. I don't think it's necessary for us to do a check again here. We can do the same type of check based on whether the API is enabled, but that's duplicated of what has been done by PF.

**Comment by xingao267** [comment]
Also given project creation and resources creation can be decoupled in separate deployments, and customers might use `raw_configs` field to use other type of GKE cluster module. It's difficult to know whether or not a cluster is requested based on resources defined in DPT.

**Comment by umairidris** [comment]
Ok, the naming of these variables is confusing. IIUC, what `grant_services_security_admin_role` do is simply *allow* the PF module to grant the role IF the correct API is enabled? If there is no API then it is a no-op?

**Comment by xingao267** [comment]
> Ok, the naming of these variables is confusing. IIUC, what `grant_services_security_admin_role` do is simply _allow_ the PF module to grant the role IF the correct API is enabled? If there is no API then it is a no-op?

Yes. Only when correct API (currently, only the GKE API) is enabled. Noop when it's not enabled.

**Review by umairidris — APPROVED** [review]

**Comment by umairidris** [comment]
Maybe clarify it is a no-op as a comment.

**Comment by xingao267** [comment]
> Maybe clarify when it is a no-op as a comment.

Done

**Pull request merged**
