### PR TITLE
Update module hashicorp/terraform to v0.13.0

### PR DESCRIPTION
**Pull request by xingao267**
Replace https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/542

### CODE REVIEW

**Comment by umairidris** [comment]
The original PR also had a bunch of related libs being upgraded. Is that not needed? Does go get -u and go mod tidy cause any updates?

**Comment by xingao267** [comment]
> The original PR also had a bunch of related libs being upgraded. Is that not needed? Does go get -u and go mod tidy cause any updates?

They are included. The `go.mod` file, for some reason` is auto-collapsed in the review tool.

**Comment by MartinPetkov** [comment]
> > The original PR also had a bunch of related libs being upgraded. Is that not needed? Does go get -u and go mod tidy cause any updates?
> 
> They are included. The `go.mod` file, for some reason` is auto-collapsed in the review tool.

It's auto-collapsed because it's too large.

**Comment by umairidris** [comment]
Ah, glossed over it. thanks

**Pull request merged**
