### PR TITLE
fix(renovate): match .tf files only for terraform manager

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Comment by MartinPetkov** [comment]
Does this fix any bug?

**Comment by rarkins** [comment]
It fixes an incorrect config, but it's not yet detected automatically by Renovate. Once we add detection then this repo would be blocked until the Pr is merged. 

You are overwriting every single manager's default fileMatch with a terraform pattern, so currently it's asking Renovate to scan .tf files for every possible manager so it's doing a massive amount of wasted work attempting to parse them as npm package.json, maven. Pom, etc.

**Comment by rarkins** [comment]
It also means all non-Terraform files are essentially ignored

**Comment by MartinPetkov** [comment]
Okay, that makes sense. Will approve.

**Review by MartinPetkov — APPROVED** [review]

**Comment by MartinPetkov** [comment]
I think this PR might have been responsible for why the gen_check is failing in github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/610. It only updated one of the files, and not the other one.

I'm going to revert it, as things were working before.

**Pull request merged**
