### PR TITLE
rm outdated todos

### PR DESCRIPTION
**Pull request by umairidris**

### CODE REVIEW

**Review by MartinPetkov — COMMENTED** [review]
There are few other TODOs with you:
* templates/tfengine/recipes/resources.hcl
* internal/tfengine/tfengine_test.go
* internal/template/template.go

**Comment by MartinPetkov** [comment]
Also CODEOWNERS

**Comment by umairidris** [comment]
Thanks, done

**Comment by MartinPetkov** [comment]
And internal/tfengine/tfengine_test.go, sorry

**Comment by umairidris** [comment]
weird, my vscode search didnt catch that.

**Review by MartinPetkov — APPROVED** [review]

**Review by xingao267 — APPROVED** [review]

**Pull request merged**
