### PR TITLE
Remove monitoring/forseti from examples.

### PR DESCRIPTION
**Pull request by xingao267**
Forseti has been deprecated and the monitoring capability of the toolkit is also no longer a priority. Having it in the examples (folder foundation, org foundation) causes confusions and issues such as https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/1061.

### CODE REVIEW

**Review by pasha-gh — COMMENTED** [review]
Can you please update the documentation and remove `monitor` from here:
https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/docs/tfengine/README.md?plain=1#L53

**Comment by xingao267** [comment]
> Can you please update the documentation and remove `monitor` from here: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/docs/tfengine/README.md?plain=1#L53

Good catch! Done.

**Review by pasha-gh — APPROVED** [review]

**Pull request merged**
