### PR TITLE
Separate the Engine integration tests

### PR DESCRIPTION
**Pull request by MartinPetkov**
Currently all tests in tfengine_test.go are non-hermetic and closer to integration tests, since they aren't Go-only tests. They expect the "terraform" binary to be installed and access GitHub Releases.

Rename this file so that if unit tests are added in the future, there's a clear separation.

### CODE REVIEW

**Comment by umairidris** [comment]
Is there supposed to be a renamed file?

**Comment by MartinPetkov** [comment]
> Is there supposed to be a renamed file?

Yes. I just added it, it was ignored by .gitignore before.

**Comment by umairidris** [comment]
I think just calling it integration_test.go for now is fine. We might have a 'full' integration test later on though that actually applies things too, so we may need a way to separate this 'semi' integration test from that.

**Review by umairidris — APPROVED** [review]

**Comment by MartinPetkov** [comment]
> I think just calling it integration_test.go for now is fine. We might have a 'full' integration test later on though that actually applies things too, so we may need a way to separate this 'semi' integration test from that.

Done.

**Pull request merged**
