### PR TITLE
Do not lock state in plan.

### PR DESCRIPTION
**Pull request by xingao267**

### CODE REVIEW

**Comment by MartinPetkov** [comment]
What is the implication of not locking? Would the plan be inconsistent sometimes (if it happens in the middle of an apply), or would it just allow plans to happen in parallel?

**Comment by xingao267** [comment]
> What is the implication of not locking? Would the plan be inconsistent sometimes (if it happens in the middle of an apply), or would it just allow plans to happen in parallel?

Yes. it could be inconsistent. So the plan in presubmit is not *always* true but just FYI. But it can be very common that multiple presubmit jobs run at the same time, or at the same time as the post-deployment job. I would like the apply job to actually grab the lock, and plan jobs just take a peek at the state.

**Pull request merged**
