### PR TITLE
Update tf-deletion-check.sh

### PR DESCRIPTION
**Pull request by jeffbryner**
syntax fix up to avoid the ./cicd/configs/tf-deletion-check.sh: line 77: unexpected EOF while looking for matching `"' error

### CODE REVIEW

**Review by MartinPetkov — APPROVED** [review]

**Comment by MartinPetkov** [comment]
From the unit tests:
```
Please run the following command from the repo root and check in the changes:
./scripts/regen.sh
```

**Comment by jeffbryner** [comment]
@googlebot I signed it!

**Comment by jeffbryner** [comment]
> From the unit tests:
> 
> ```
> Please run the following command from the repo root and check in the changes:
> ./scripts/regen.sh
> ```

sorry, just realized this script lives in multiple places and checked in what I think is the main file (templates/tfengine/components/cicd/configs). Ran the regen.sh script and there is no diff in the tf-deletion-check.sh in other directories, but I'm not sure the script works

**Comment by MartinPetkov** [comment]
> > From the unit tests:
> > ```
> > Please run the following command from the repo root and check in the changes:
> > ./scripts/regen.sh
> > ```
> 
> sorry, just realized this script lives in multiple places and checked in what I think is the main file (templates/tfengine/components/cicd/configs). Ran the regen.sh script and there is no diff in the tf-deletion-check.sh in other directories, but I'm not sure the script works

The regen script definitely works, but you might need a Go environment.

I've opened https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/1021 instead.

**Pull request closed without merging**
