### PR TITLE
Suppress verbose terragrunt outputs.

### LINKED ISSUE #15: Support filtering plans so the log is more readable.

### PR DESCRIPTION
**Pull request by xingao267**
Fixes #15

### CODE REVIEW

**Comment by xingao267** [comment]
Sample: https://console.cloud.google.com/cloud-build/builds/712f4fd0-47ef-4609-a0fd-8407ba00faa4?project=dpt-demo-3-devops

https://console.cloud.google.com/cloud-build/builds/c04ebb0a-99e4-43af-80d1-ba871b4f297c;step=6?project=dpt-demo-3-devops

**Comment by umairidris** [comment]
Also, do we still need deletion check if we have cleaner plans?

**Comment by xingao267** [comment]
terragrunt output like the following are still there:

[terragrunt] [/workspace/live/org_policies] 2020/05/11 21:21:48 Running module /workspace/live/org_policies now
[terragrunt] [/workspace/live/audit/project] 2020/05/11 21:21:48 Running module /workspace/live/audit/project now
[terragrunt] [/workspace/live/monitor/project] 2020/05/11 21:21:48 Running module /workspace/live/monitor/project now
[terragrunt] [/workspace/live/monitor/forseti] 2020/05/11 21:22:13 Running module /workspace/live/monitor/forseti now
[terragrunt] [/workspace/live/audit/resources] 2020/05/11 21:22:14 Running module /workspace/live/audit/resources now

**Comment by umairidris** [comment]
Got it, this looks great! Thanks for working on it. Much better than before.

**Comment by xingao267** [comment]
I think the deletion check is still great to have as the plan is still verbose in the terraform part. So it's one place that simply tell users about deletion. We could combine that step with plan, But I'm also looking into how to name the steps better so it's more human readable than a command or arguments. We can improve that in a separate PR.

**Pull request merged**
